"""Initial migration

Revision ID: 64319b1f9e8f
Revises: 7ec3cf83eb3c
Create Date: 2024-11-24 19:14:36.869404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64319b1f9e8f'
down_revision = '7ec3cf83eb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('body_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('drive_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('horsepower',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('horsepower',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('drive_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('body_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
