"""Initial migration

Revision ID: 7ec3cf83eb3c
Revises: 
Create Date: 2024-11-24 19:11:25.093001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec3cf83eb3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autosalon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIO', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_salon', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('brend', sa.String(length=150), nullable=False),
    sa.Column('body_type', sa.String(length=30), nullable=True),
    sa.Column('drive_type', sa.String(length=30), nullable=True),
    sa.Column('VIN', sa.String(length=17), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('horsepower', sa.Integer(), nullable=True),
    sa.Column('type_fuel', sa.String(length=50), nullable=False),
    sa.Column('fuel_consumption', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('motor_volume', sa.String(length=10), nullable=False),
    sa.Column('transmission', sa.String(length=20), nullable=False),
    sa.Column('reliable', sa.Boolean(), nullable=False),
    sa.Column('economical', sa.Boolean(), nullable=False),
    sa.Column('for_evening_walk', sa.Boolean(), nullable=False),
    sa.Column('aesthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_salon'], ['autosalon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_salon', sa.Integer(), nullable=False),
    sa.Column('FIO', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_salon'], ['autosalon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_manager', sa.Integer(), nullable=False),
    sa.Column('id_cars', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_cars'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['id_manager'], ['manager.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('manager')
    op.drop_table('cars')
    op.drop_table('users')
    op.drop_table('autosalon')
    # ### end Alembic commands ###
